/**
 * Type definitions for the question data and answer records.
 *
 * The questions.json file is generated by scripts/extract-questions.mjs.
 * The lessons.json file is hand-curated (see plan §M5.2).
 */

export type QuestionType = "conceptual" | "numerical";

export interface Question {
  id: string;
  number: number;
  module: string;
  lesson: string;
  type: QuestionType;
  prompt: string;
}

export interface Lesson {
  module: string;
  name: string;
  questionCount: number;
  questionIds: string[];
}

export interface QuestionBank {
  questions: Question[];
  lessons: Lesson[];
}

export type Verdict = "correct" | "partial" | "incorrect";

export interface Answer {
  id: string;
  esis: string;
  question_id: string;
  lesson: string;
  module: string;
  student_answer: string;
  ai_verdict: Verdict;
  ai_feedback: string;
  submitted_at: string;
}

/* ------------------------------------------------------------------ */
/* M5.2 — Paged lesson content (slides + image refs)                  */
/* ------------------------------------------------------------------ */

export type SlideSource = "manual" | "docx" | "ai";

export interface ImageRef {
  /** Public path served by Vite, e.g. "/images/lessons/image3.png". */
  src: string;
  alt: string;
  caption?: string;
}

export interface FormulaRef {
  label: string;
  expression: string;
}

export interface Slide {
  id: string;
  title: string;
  /** Markdown body. Use **bold** for key terms, plain text otherwise. */
  body: string;
  image?: ImageRef;
  formula?: FormulaRef;
  source: SlideSource;
}

export interface LessonWithSlides {
  /** Stable URL slug, unique across all lessons (e.g. "gravitation"). */
  id: string;
  module: string;
  name: string;
  /** Last word of `name`, italicized in gold on the lesson card / hero. */
  accentWord: string;
  /** Short pitch shown on the home card and as a hero subtitle. */
  description: string;
  slides: Slide[];
  questionIds: string[];
  /**
   * Derived: `questionIds.length`. Set when the data is loaded by
   * `lessons.ts` so consumers (LessonCard, useLearningPath) can read
   * the count without re-computing.
   */
  questionCount: number;
}

export interface LessonsFile {
  lessons: LessonWithSlides[];
}

/** Q-ID → image filename, used by the question-image wire-up (M5.6). */
export interface QuestionImageMap {
  [questionId: string]: {
    src: string;
    alt: string;
  } | null;
}

export interface QuestionImagesFile {
  generated_at: string;
  total: number;
  images: Record<string, { src: string; alt: string }>;
}
