/**
 * Type definitions for the question data and answer records.
 *
 * The questions.json file is generated by scripts/extract-questions.mjs.
 */

export type QuestionType = "conceptual" | "numerical";

export interface Question {
  id: string;
  number: number;
  module: string;
  lesson: string;
  type: QuestionType;
  prompt: string;
}

export interface Lesson {
  module: string;
  name: string;
  questionCount: number;
  questionIds: string[];
}

export interface QuestionBank {
  questions: Question[];
  lessons: Lesson[];
}

export type Verdict = "correct" | "partial" | "incorrect";

export interface Answer {
  id: string;
  esis: string;
  question_id: string;
  lesson: string;
  module: string;
  student_answer: string;
  ai_verdict: Verdict;
  ai_feedback: string;
  submitted_at: string;
}
